// Code generated by cmd/reset; DO NOT EDIT.

package dto

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		if resetter, ok := interface{}(r.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}

func (r *ComplexStruct) Reset() {
	if r == nil {
		return
	}

	r.ID = 0
	r.Name = ""
	r.Active = false
	r.Tags = r.Tags[:0]
	clear(r.Metadata)
	if r.Parent != nil {
		if resetter, ok := interface{}(r.Parent).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
	if r.Count != nil {
		*r.Count = 0
	}
	if r.Score != nil {
		*r.Score = 0
	}
}

func (r *SimpleStruct) Reset() {
	if r == nil {
		return
	}

	r.Value = 0
	r.Label = ""
}
